<?php
/**
 * V4authoritiesApi
 * PHP version 5
 *
 * @category Class
 * @package  SierraApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace SierraApi\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use SierraApi\ApiException;
use SierraApi\Configuration;
use SierraApi\HeaderSelector;
use SierraApi\ObjectSerializer;

/**
 * V4authoritiesApi Class Doc Comment
 *
 * @category Class
 * @package  SierraApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class V4authoritiesApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation filterTheRecordsByAQueryInJSONFormat
     *
     * Filter the records by a query in JSON format
     *
     * @param  int $offset the beginning record (zero-indexed) of the result set returned (required)
     * @param  int $limit the maximum number of results (required)
     * @param   $json a query in JSON format (see the Sierra API reference documentation for more information) (required)
     *
     * @throws \SierraApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \SierraApi\Model\QueryResultSet
     */
    public function filterTheRecordsByAQueryInJSONFormat($offset, $limit, $json)
    {
        list($response) = $this->filterTheRecordsByAQueryInJSONFormatWithHttpInfo($offset, $limit, $json);
        return $response;
    }

    /**
     * Operation filterTheRecordsByAQueryInJSONFormatWithHttpInfo
     *
     * Filter the records by a query in JSON format
     *
     * @param  int $offset the beginning record (zero-indexed) of the result set returned (required)
     * @param  int $limit the maximum number of results (required)
     * @param   $json a query in JSON format (see the Sierra API reference documentation for more information) (required)
     *
     * @throws \SierraApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \SierraApi\Model\QueryResultSet, HTTP status code, HTTP response headers (array of strings)
     */
    public function filterTheRecordsByAQueryInJSONFormatWithHttpInfo($offset, $limit, $json)
    {
        $returnType = '\SierraApi\Model\QueryResultSet';
        $request = $this->filterTheRecordsByAQueryInJSONFormatRequest($offset, $limit, $json);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse()->getBody()->getContents()
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SierraApi\Model\QueryResultSet',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation filterTheRecordsByAQueryInJSONFormatAsync
     *
     * Filter the records by a query in JSON format
     *
     * @param  int $offset the beginning record (zero-indexed) of the result set returned (required)
     * @param  int $limit the maximum number of results (required)
     * @param   $json a query in JSON format (see the Sierra API reference documentation for more information) (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function filterTheRecordsByAQueryInJSONFormatAsync($offset, $limit, $json)
    {
        return $this->filterTheRecordsByAQueryInJSONFormatAsyncWithHttpInfo($offset, $limit, $json)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation filterTheRecordsByAQueryInJSONFormatAsyncWithHttpInfo
     *
     * Filter the records by a query in JSON format
     *
     * @param  int $offset the beginning record (zero-indexed) of the result set returned (required)
     * @param  int $limit the maximum number of results (required)
     * @param   $json a query in JSON format (see the Sierra API reference documentation for more information) (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function filterTheRecordsByAQueryInJSONFormatAsyncWithHttpInfo($offset, $limit, $json)
    {
        $returnType = '\SierraApi\Model\QueryResultSet';
        $request = $this->filterTheRecordsByAQueryInJSONFormatRequest($offset, $limit, $json);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'filterTheRecordsByAQueryInJSONFormat'
     *
     * @param  int $offset the beginning record (zero-indexed) of the result set returned (required)
     * @param  int $limit the maximum number of results (required)
     * @param   $json a query in JSON format (see the Sierra API reference documentation for more information) (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function filterTheRecordsByAQueryInJSONFormatRequest($offset, $limit, $json)
    {
        // verify the required parameter 'offset' is set
        if ($offset === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $offset when calling filterTheRecordsByAQueryInJSONFormat'
            );
        }
        // verify the required parameter 'limit' is set
        if ($limit === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $limit when calling filterTheRecordsByAQueryInJSONFormat'
            );
        }
        // verify the required parameter 'json' is set
        if ($json === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $json when calling filterTheRecordsByAQueryInJSONFormat'
            );
        }

        $resourcePath = '/v4/authorities/query';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($offset !== null) {
            $queryParams['offset'] = ObjectSerializer::toQueryValue($offset);
        }
        // query params
        if ($limit !== null) {
            $queryParams['limit'] = ObjectSerializer::toQueryValue($limit);
        }


        // body params
        $_tempBody = null;
        if (isset($json)) {
            $_tempBody = $json;
        }

        if ($multipart) {
            $headers= $this->headerSelector->selectHeadersForMultipart(
                ['application/json', 'application/xml']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json', 'application/xml'],
                ['application/json', 'application/xml']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getAListOfAuthorityRecords
     *
     * Get a list of authority records
     *
     * @param  int $limit the maximum number of results (optional)
     * @param  int $offset the beginning record (zero-indexed) of the result set returned (optional)
     * @param  int[] $id a comma-delimited list of IDs of authority records to retrieve (optional)
     * @param  string[] $fields a comma-delimited list of fields to retrieve (optional)
     * @param  \DateTime $created_date the creation date of authority records to retrieve (can be a range) (optional)
     * @param  \DateTime $updated_date the modification date of authority records to retrieve (can be a range) (optional)
     * @param  \DateTime $deleted_date the deletion date of deleted authority records to retrieve (can be a range) (optional)
     * @param  bool $deleted whether to retrieve only deleted (true) or non-deleted (false) authority records (optional)
     * @param  bool $suppressed the suppressed flag value of authority records to retrieve (optional)
     *
     * @throws \SierraApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \SierraApi\Model\AuthorityResultSet
     */
    public function getAListOfAuthorityRecords($limit = null, $offset = null, $id = null, $fields = null, $created_date = null, $updated_date = null, $deleted_date = null, $deleted = null, $suppressed = null)
    {
        list($response) = $this->getAListOfAuthorityRecordsWithHttpInfo($limit, $offset, $id, $fields, $created_date, $updated_date, $deleted_date, $deleted, $suppressed);
        return $response;
    }

    /**
     * Operation getAListOfAuthorityRecordsWithHttpInfo
     *
     * Get a list of authority records
     *
     * @param  int $limit the maximum number of results (optional)
     * @param  int $offset the beginning record (zero-indexed) of the result set returned (optional)
     * @param  int[] $id a comma-delimited list of IDs of authority records to retrieve (optional)
     * @param  string[] $fields a comma-delimited list of fields to retrieve (optional)
     * @param  \DateTime $created_date the creation date of authority records to retrieve (can be a range) (optional)
     * @param  \DateTime $updated_date the modification date of authority records to retrieve (can be a range) (optional)
     * @param  \DateTime $deleted_date the deletion date of deleted authority records to retrieve (can be a range) (optional)
     * @param  bool $deleted whether to retrieve only deleted (true) or non-deleted (false) authority records (optional)
     * @param  bool $suppressed the suppressed flag value of authority records to retrieve (optional)
     *
     * @throws \SierraApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \SierraApi\Model\AuthorityResultSet, HTTP status code, HTTP response headers (array of strings)
     */
    public function getAListOfAuthorityRecordsWithHttpInfo($limit = null, $offset = null, $id = null, $fields = null, $created_date = null, $updated_date = null, $deleted_date = null, $deleted = null, $suppressed = null)
    {
        $returnType = '\SierraApi\Model\AuthorityResultSet';
        $request = $this->getAListOfAuthorityRecordsRequest($limit, $offset, $id, $fields, $created_date, $updated_date, $deleted_date, $deleted, $suppressed);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse()->getBody()->getContents()
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SierraApi\Model\AuthorityResultSet',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getAListOfAuthorityRecordsAsync
     *
     * Get a list of authority records
     *
     * @param  int $limit the maximum number of results (optional)
     * @param  int $offset the beginning record (zero-indexed) of the result set returned (optional)
     * @param  int[] $id a comma-delimited list of IDs of authority records to retrieve (optional)
     * @param  string[] $fields a comma-delimited list of fields to retrieve (optional)
     * @param  \DateTime $created_date the creation date of authority records to retrieve (can be a range) (optional)
     * @param  \DateTime $updated_date the modification date of authority records to retrieve (can be a range) (optional)
     * @param  \DateTime $deleted_date the deletion date of deleted authority records to retrieve (can be a range) (optional)
     * @param  bool $deleted whether to retrieve only deleted (true) or non-deleted (false) authority records (optional)
     * @param  bool $suppressed the suppressed flag value of authority records to retrieve (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAListOfAuthorityRecordsAsync($limit = null, $offset = null, $id = null, $fields = null, $created_date = null, $updated_date = null, $deleted_date = null, $deleted = null, $suppressed = null)
    {
        return $this->getAListOfAuthorityRecordsAsyncWithHttpInfo($limit, $offset, $id, $fields, $created_date, $updated_date, $deleted_date, $deleted, $suppressed)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getAListOfAuthorityRecordsAsyncWithHttpInfo
     *
     * Get a list of authority records
     *
     * @param  int $limit the maximum number of results (optional)
     * @param  int $offset the beginning record (zero-indexed) of the result set returned (optional)
     * @param  int[] $id a comma-delimited list of IDs of authority records to retrieve (optional)
     * @param  string[] $fields a comma-delimited list of fields to retrieve (optional)
     * @param  \DateTime $created_date the creation date of authority records to retrieve (can be a range) (optional)
     * @param  \DateTime $updated_date the modification date of authority records to retrieve (can be a range) (optional)
     * @param  \DateTime $deleted_date the deletion date of deleted authority records to retrieve (can be a range) (optional)
     * @param  bool $deleted whether to retrieve only deleted (true) or non-deleted (false) authority records (optional)
     * @param  bool $suppressed the suppressed flag value of authority records to retrieve (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAListOfAuthorityRecordsAsyncWithHttpInfo($limit = null, $offset = null, $id = null, $fields = null, $created_date = null, $updated_date = null, $deleted_date = null, $deleted = null, $suppressed = null)
    {
        $returnType = '\SierraApi\Model\AuthorityResultSet';
        $request = $this->getAListOfAuthorityRecordsRequest($limit, $offset, $id, $fields, $created_date, $updated_date, $deleted_date, $deleted, $suppressed);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getAListOfAuthorityRecords'
     *
     * @param  int $limit the maximum number of results (optional)
     * @param  int $offset the beginning record (zero-indexed) of the result set returned (optional)
     * @param  int[] $id a comma-delimited list of IDs of authority records to retrieve (optional)
     * @param  string[] $fields a comma-delimited list of fields to retrieve (optional)
     * @param  \DateTime $created_date the creation date of authority records to retrieve (can be a range) (optional)
     * @param  \DateTime $updated_date the modification date of authority records to retrieve (can be a range) (optional)
     * @param  \DateTime $deleted_date the deletion date of deleted authority records to retrieve (can be a range) (optional)
     * @param  bool $deleted whether to retrieve only deleted (true) or non-deleted (false) authority records (optional)
     * @param  bool $suppressed the suppressed flag value of authority records to retrieve (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getAListOfAuthorityRecordsRequest($limit = null, $offset = null, $id = null, $fields = null, $created_date = null, $updated_date = null, $deleted_date = null, $deleted = null, $suppressed = null)
    {

        $resourcePath = '/v4/authorities/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($limit !== null) {
            $queryParams['limit'] = ObjectSerializer::toQueryValue($limit);
        }
        // query params
        if ($offset !== null) {
            $queryParams['offset'] = ObjectSerializer::toQueryValue($offset);
        }
        // query params
        if (is_array($id)) {
            $id = ObjectSerializer::serializeCollection($id, 'csv', true);
        }
        if ($id !== null) {
            $queryParams['id'] = ObjectSerializer::toQueryValue($id);
        }
        // query params
        if (is_array($fields)) {
            $fields = ObjectSerializer::serializeCollection($fields, 'csv', true);
        }
        if ($fields !== null) {
            $queryParams['fields'] = ObjectSerializer::toQueryValue($fields);
        }
        // query params
        if ($created_date !== null) {
            $queryParams['createdDate'] = ObjectSerializer::toQueryValue($created_date);
        }
        // query params
        if ($updated_date !== null) {
            $queryParams['updatedDate'] = ObjectSerializer::toQueryValue($updated_date);
        }
        // query params
        if ($deleted_date !== null) {
            $queryParams['deletedDate'] = ObjectSerializer::toQueryValue($deleted_date);
        }
        // query params
        if ($deleted !== null) {
            $queryParams['deleted'] = ObjectSerializer::toQueryValue($deleted);
        }
        // query params
        if ($suppressed !== null) {
            $queryParams['suppressed'] = ObjectSerializer::toQueryValue($suppressed);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers= $this->headerSelector->selectHeadersForMultipart(
                ['application/json', 'application/xml']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json', 'application/xml'],
                ['application/json', 'application/xml']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getAnAuthorityRecordByRecordID
     *
     * Get an authority record by record ID
     *
     * @param  int $id the authority record ID (required)
     * @param  string[] $fields a comma-delimited list of fields to retrieve (optional)
     *
     * @throws \SierraApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \SierraApi\Model\Authority
     */
    public function getAnAuthorityRecordByRecordID($id, $fields = null)
    {
        list($response) = $this->getAnAuthorityRecordByRecordIDWithHttpInfo($id, $fields);
        return $response;
    }

    /**
     * Operation getAnAuthorityRecordByRecordIDWithHttpInfo
     *
     * Get an authority record by record ID
     *
     * @param  int $id the authority record ID (required)
     * @param  string[] $fields a comma-delimited list of fields to retrieve (optional)
     *
     * @throws \SierraApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \SierraApi\Model\Authority, HTTP status code, HTTP response headers (array of strings)
     */
    public function getAnAuthorityRecordByRecordIDWithHttpInfo($id, $fields = null)
    {
        $returnType = '\SierraApi\Model\Authority';
        $request = $this->getAnAuthorityRecordByRecordIDRequest($id, $fields);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse()->getBody()->getContents()
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SierraApi\Model\Authority',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getAnAuthorityRecordByRecordIDAsync
     *
     * Get an authority record by record ID
     *
     * @param  int $id the authority record ID (required)
     * @param  string[] $fields a comma-delimited list of fields to retrieve (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAnAuthorityRecordByRecordIDAsync($id, $fields = null)
    {
        return $this->getAnAuthorityRecordByRecordIDAsyncWithHttpInfo($id, $fields)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getAnAuthorityRecordByRecordIDAsyncWithHttpInfo
     *
     * Get an authority record by record ID
     *
     * @param  int $id the authority record ID (required)
     * @param  string[] $fields a comma-delimited list of fields to retrieve (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAnAuthorityRecordByRecordIDAsyncWithHttpInfo($id, $fields = null)
    {
        $returnType = '\SierraApi\Model\Authority';
        $request = $this->getAnAuthorityRecordByRecordIDRequest($id, $fields);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getAnAuthorityRecordByRecordID'
     *
     * @param  int $id the authority record ID (required)
     * @param  string[] $fields a comma-delimited list of fields to retrieve (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getAnAuthorityRecordByRecordIDRequest($id, $fields = null)
    {
        // verify the required parameter 'id' is set
        if ($id === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling getAnAuthorityRecordByRecordID'
            );
        }

        $resourcePath = '/v4/authorities/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if (is_array($fields)) {
            $fields = ObjectSerializer::serializeCollection($fields, 'csv', true);
        }
        if ($fields !== null) {
            $queryParams['fields'] = ObjectSerializer::toQueryValue($fields);
        }

        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers= $this->headerSelector->selectHeadersForMultipart(
                ['application/json', 'application/xml']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json', 'application/xml'],
                ['application/json', 'application/xml']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getTheMARCDataForASingleAuthorityRecord
     *
     * Get the MARC data for a single authority record
     *
     * @param  int $id the authority record ID (required)
     *
     * @throws \SierraApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \SierraApi\Model\ErrorCode
     */
    public function getTheMARCDataForASingleAuthorityRecord($id)
    {
        list($response) = $this->getTheMARCDataForASingleAuthorityRecordWithHttpInfo($id);
        return $response;
    }

    /**
     * Operation getTheMARCDataForASingleAuthorityRecordWithHttpInfo
     *
     * Get the MARC data for a single authority record
     *
     * @param  int $id the authority record ID (required)
     *
     * @throws \SierraApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \SierraApi\Model\ErrorCode, HTTP status code, HTTP response headers (array of strings)
     */
    public function getTheMARCDataForASingleAuthorityRecordWithHttpInfo($id)
    {
        $returnType = '\SierraApi\Model\ErrorCode';
        $request = $this->getTheMARCDataForASingleAuthorityRecordRequest($id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse()->getBody()->getContents()
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SierraApi\Model\ErrorCode',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getTheMARCDataForASingleAuthorityRecordAsync
     *
     * Get the MARC data for a single authority record
     *
     * @param  int $id the authority record ID (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getTheMARCDataForASingleAuthorityRecordAsync($id)
    {
        return $this->getTheMARCDataForASingleAuthorityRecordAsyncWithHttpInfo($id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getTheMARCDataForASingleAuthorityRecordAsyncWithHttpInfo
     *
     * Get the MARC data for a single authority record
     *
     * @param  int $id the authority record ID (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getTheMARCDataForASingleAuthorityRecordAsyncWithHttpInfo($id)
    {
        $returnType = '\SierraApi\Model\ErrorCode';
        $request = $this->getTheMARCDataForASingleAuthorityRecordRequest($id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getTheMARCDataForASingleAuthorityRecord'
     *
     * @param  int $id the authority record ID (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getTheMARCDataForASingleAuthorityRecordRequest($id)
    {
        // verify the required parameter 'id' is set
        if ($id === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling getTheMARCDataForASingleAuthorityRecord'
            );
        }

        $resourcePath = '/v4/authorities/{id}/marc';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers= $this->headerSelector->selectHeadersForMultipart(
                ['application/marc-json', 'application/marc-xml', 'application/marc-in-json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/marc-json', 'application/marc-xml', 'application/marc-in-json'],
                ['application/json', 'application/xml']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
