<?php
/**
 * OrderTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  SierraApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace SierraApi;

/**
 * OrderTest Class Doc Comment
 *
 * @category    Class */
// * @description the order
/**
 * @package     SierraApi
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OrderTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Order"
     */
    public function testOrder()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "updated_date"
     */
    public function testPropertyUpdatedDate()
    {
    }

    /**
     * Test attribute "created_date"
     */
    public function testPropertyCreatedDate()
    {
    }

    /**
     * Test attribute "deleted_date"
     */
    public function testPropertyDeletedDate()
    {
    }

    /**
     * Test attribute "deleted"
     */
    public function testPropertyDeleted()
    {
    }

    /**
     * Test attribute "suppressed"
     */
    public function testPropertySuppressed()
    {
    }

    /**
     * Test attribute "accounting_unit"
     */
    public function testPropertyAccountingUnit()
    {
    }

    /**
     * Test attribute "estimated_price"
     */
    public function testPropertyEstimatedPrice()
    {
    }

    /**
     * Test attribute "vendor_record_code"
     */
    public function testPropertyVendorRecordCode()
    {
    }

    /**
     * Test attribute "order_date"
     */
    public function testPropertyOrderDate()
    {
    }

    /**
     * Test attribute "charged_funds"
     */
    public function testPropertyChargedFunds()
    {
    }

    /**
     * Test attribute "vendor_titles"
     */
    public function testPropertyVendorTitles()
    {
    }

    /**
     * Test attribute "fixed_fields"
     */
    public function testPropertyFixedFields()
    {
    }

    /**
     * Test attribute "var_fields"
     */
    public function testPropertyVarFields()
    {
    }
}
