<?php
/**
 * AdminSettingsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Sierra
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Sierra;

/**
 * AdminSettingsTest Class Doc Comment
 *
 * @category    Class */
// * @description Administrator settings
/**
 * @package     Sierra
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AdminSettingsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AdminSettings"
     */
    public function testAdminSettings()
    {
    }

    /**
     * Test attribute "can_config"
     */
    public function testPropertyCanConfig()
    {
    }

    /**
     * Test attribute "access_tier"
     */
    public function testPropertyAccessTier()
    {
    }

    /**
     * Test attribute "root_url"
     */
    public function testPropertyRootUrl()
    {
    }

    /**
     * Test attribute "email_sender_name"
     */
    public function testPropertyEmailSenderName()
    {
    }

    /**
     * Test attribute "email_sender_email"
     */
    public function testPropertyEmailSenderEmail()
    {
    }

    /**
     * Test attribute "email_subject"
     */
    public function testPropertyEmailSubject()
    {
    }

    /**
     * Test attribute "email_host"
     */
    public function testPropertyEmailHost()
    {
    }

    /**
     * Test attribute "email_user"
     */
    public function testPropertyEmailUser()
    {
    }

    /**
     * Test attribute "api_enabled"
     */
    public function testPropertyApiEnabled()
    {
    }
}
