<?php
/**
 * FineTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Sierra
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 5
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Sierra;

/**
 * FineTest Class Doc Comment
 *
 * @category    Class */
// * @description a patron fine
/**
 * @package     Sierra
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FineTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Fine"
     */
    public function testFine()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "patron"
     */
    public function testPropertyPatron()
    {
    }

    /**
     * Test attribute "item"
     */
    public function testPropertyItem()
    {
    }

    /**
     * Test attribute "assessed_date"
     */
    public function testPropertyAssessedDate()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "invoice_number"
     */
    public function testPropertyInvoiceNumber()
    {
    }

    /**
     * Test attribute "charge_type"
     */
    public function testPropertyChargeType()
    {
    }

    /**
     * Test attribute "item_charge"
     */
    public function testPropertyItemCharge()
    {
    }

    /**
     * Test attribute "processing_fee"
     */
    public function testPropertyProcessingFee()
    {
    }

    /**
     * Test attribute "billing_fee"
     */
    public function testPropertyBillingFee()
    {
    }

    /**
     * Test attribute "paid_amount"
     */
    public function testPropertyPaidAmount()
    {
    }

    /**
     * Test attribute "location"
     */
    public function testPropertyLocation()
    {
    }

    /**
     * Test attribute "initials"
     */
    public function testPropertyInitials()
    {
    }

    /**
     * Test attribute "creation_method"
     */
    public function testPropertyCreationMethod()
    {
    }

    /**
     * Test attribute "date_paid"
     */
    public function testPropertyDatePaid()
    {
    }

    /**
     * Test attribute "original_patron"
     */
    public function testPropertyOriginalPatron()
    {
    }

    /**
     * Test attribute "print_bill"
     */
    public function testPropertyPrintBill()
    {
    }

    /**
     * Test attribute "terminal_number"
     */
    public function testPropertyTerminalNumber()
    {
    }

    /**
     * Test attribute "transfer_date"
     */
    public function testPropertyTransferDate()
    {
    }

    /**
     * Test attribute "return_date"
     */
    public function testPropertyReturnDate()
    {
    }
}
