<?php
/**
 * InvoiceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  III\Sierra
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 5
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace III\Sierra;

/**
 * InvoiceTest Class Doc Comment
 *
 * @category    Class */
// * @description an invoice record
/**
 * @package     III\Sierra
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InvoiceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Invoice"
     */
    public function testInvoice()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "accountingUnit"
     */
    public function testPropertyAccountingUnit()
    {
    }

    /**
     * Test attribute "invDate"
     */
    public function testPropertyInvDate()
    {
    }

    /**
     * Test attribute "invNum"
     */
    public function testPropertyInvNum()
    {
    }

    /**
     * Test attribute "taxType"
     */
    public function testPropertyTaxType()
    {
    }

    /**
     * Test attribute "vendors"
     */
    public function testPropertyVendors()
    {
    }

    /**
     * Test attribute "paidDate"
     */
    public function testPropertyPaidDate()
    {
    }

    /**
     * Test attribute "forCurrency"
     */
    public function testPropertyForCurrency()
    {
    }

    /**
     * Test attribute "invTotal"
     */
    public function testPropertyInvTotal()
    {
    }

    /**
     * Test attribute "useTax"
     */
    public function testPropertyUseTax()
    {
    }

    /**
     * Test attribute "lineItems"
     */
    public function testPropertyLineItems()
    {
    }
}
