<?php
/**
 * PinVerificationSettingsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Sierra
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 5
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Sierra;

/**
 * PinVerificationSettingsTest Class Doc Comment
 *
 * @category    Class */
// * @description the settings for PIN verification
/**
 * @package     Sierra
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PinVerificationSettingsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PinVerificationSettings"
     */
    public function testPinVerificationSettings()
    {
    }

    /**
     * Test attribute "minimum_chars"
     */
    public function testPropertyMinimumChars()
    {
    }

    /**
     * Test attribute "maximum_chars"
     */
    public function testPropertyMaximumChars()
    {
    }

    /**
     * Test attribute "num_only"
     */
    public function testPropertyNumOnly()
    {
    }

    /**
     * Test attribute "mixed"
     */
    public function testPropertyMixed()
    {
    }
}
