<?php
/**
 * DisplayableApiInfo
 *
 * PHP version 5
 *
 * @category Class
 * @package  III\Sierra\V5
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 5
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: unset
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace III\Sierra\V5\Models;

use \ArrayAccess;
use \III\Sierra\V5\ObjectSerializer;

/**
 * DisplayableApiInfo Class Doc Comment
 *
 * @category Class
 * @description API displayable information details
 * @package  III\Sierra\V5
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DisplayableApiInfo implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'DisplayableApiInfo';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'name' => 'string',
        'version' => 'string',
        'sierraVersion' => 'string',
        'fullVersion' => 'string',
        'revision' => 'string',
        'revisionDate' => 'string',
        'backwardsCompatibleVersions' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'name' => null,
        'version' => null,
        'sierraVersion' => null,
        'fullVersion' => null,
        'revision' => null,
        'revisionDate' => null,
        'backwardsCompatibleVersions' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'name' => 'name',
        'version' => 'version',
        'sierraVersion' => 'sierraVersion',
        'fullVersion' => 'fullVersion',
        'revision' => 'revision',
        'revisionDate' => 'revisionDate',
        'backwardsCompatibleVersions' => 'backwardsCompatibleVersions'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'name' => 'setName',
        'version' => 'setVersion',
        'sierraVersion' => 'setSierraVersion',
        'fullVersion' => 'setFullVersion',
        'revision' => 'setRevision',
        'revisionDate' => 'setRevisionDate',
        'backwardsCompatibleVersions' => 'setBackwardsCompatibleVersions'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'name' => 'getName',
        'version' => 'getVersion',
        'sierraVersion' => 'getSierraVersion',
        'fullVersion' => 'getFullVersion',
        'revision' => 'getRevision',
        'revisionDate' => 'getRevisionDate',
        'backwardsCompatibleVersions' => 'getBackwardsCompatibleVersions'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['version'] = isset($data['version']) ? $data['version'] : null;
        $this->container['sierraVersion'] = isset($data['sierraVersion']) ? $data['sierraVersion'] : null;
        $this->container['fullVersion'] = isset($data['fullVersion']) ? $data['fullVersion'] : null;
        $this->container['revision'] = isset($data['revision']) ? $data['revision'] : null;
        $this->container['revisionDate'] = isset($data['revisionDate']) ? $data['revisionDate'] : null;
        $this->container['backwardsCompatibleVersions'] = isset($data['backwardsCompatibleVersions']) ? $data['backwardsCompatibleVersions'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['version'] === null) {
            $invalidProperties[] = "'version' can't be null";
        }
        if ($this->container['sierraVersion'] === null) {
            $invalidProperties[] = "'sierraVersion' can't be null";
        }
        if ($this->container['fullVersion'] === null) {
            $invalidProperties[] = "'fullVersion' can't be null";
        }
        if ($this->container['revision'] === null) {
            $invalidProperties[] = "'revision' can't be null";
        }
        if ($this->container['revisionDate'] === null) {
            $invalidProperties[] = "'revisionDate' can't be null";
        }
        if ($this->container['backwardsCompatibleVersions'] === null) {
            $invalidProperties[] = "'backwardsCompatibleVersions' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name the API name
     *
     * @return $this
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets version
     *
     * @return string
     */
    public function getVersion()
    {
        return $this->container['version'];
    }

    /**
     * Sets version
     *
     * @param string $version the API version
     *
     * @return $this
     */
    public function setVersion($version)
    {
        $this->container['version'] = $version;

        return $this;
    }

    /**
     * Gets sierraVersion
     *
     * @return string
     */
    public function getSierraVersion()
    {
        return $this->container['sierraVersion'];
    }

    /**
     * Sets sierraVersion
     *
     * @param string $sierraVersion the intended version of sierra the API works with
     *
     * @return $this
     */
    public function setSierraVersion($sierraVersion)
    {
        $this->container['sierraVersion'] = $sierraVersion;

        return $this;
    }

    /**
     * Gets fullVersion
     *
     * @return string
     */
    public function getFullVersion()
    {
        return $this->container['fullVersion'];
    }

    /**
     * Sets fullVersion
     *
     * @param string $fullVersion the full version, includes sierra version and API version
     *
     * @return $this
     */
    public function setFullVersion($fullVersion)
    {
        $this->container['fullVersion'] = $fullVersion;

        return $this;
    }

    /**
     * Gets revision
     *
     * @return string
     */
    public function getRevision()
    {
        return $this->container['revision'];
    }

    /**
     * Sets revision
     *
     * @param string $revision the API revision
     *
     * @return $this
     */
    public function setRevision($revision)
    {
        $this->container['revision'] = $revision;

        return $this;
    }

    /**
     * Gets revisionDate
     *
     * @return string
     */
    public function getRevisionDate()
    {
        return $this->container['revisionDate'];
    }

    /**
     * Sets revisionDate
     *
     * @param string $revisionDate the API revision date
     *
     * @return $this
     */
    public function setRevisionDate($revisionDate)
    {
        $this->container['revisionDate'] = $revisionDate;

        return $this;
    }

    /**
     * Gets backwardsCompatibleVersions
     *
     * @return string
     */
    public function getBackwardsCompatibleVersions()
    {
        return $this->container['backwardsCompatibleVersions'];
    }

    /**
     * Sets backwardsCompatibleVersions
     *
     * @param string $backwardsCompatibleVersions the previous versions of the API this version supports
     *
     * @return $this
     */
    public function setBackwardsCompatibleVersions($backwardsCompatibleVersions)
    {
        $this->container['backwardsCompatibleVersions'] = $backwardsCompatibleVersions;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


